/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every document in the reference corpus
         * @description `id`, `title`, and `authors` only — never the abstract.
         */
        get: operations["listCorpus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one document plus its full abstract */
        get: operations["getCorpusDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/similarity/algorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The catalogue of the six similarity capabilities
         * @description Exactly six ids, including `needleman-wunsch`.
         */
        get: operations["listSimilarityAlgorithms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/similarity/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Multi-algorithm pairwise similarity for two documents
         * @description `algorithmIds` is optional; omitted or `null` defaults to all six capabilities, so the default request already exercises every capability.
         */
        post: operations["compareSimilarity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/similarity/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * m x m similarity matrix for one algorithm over a document selection
         * @description m = selection size, business rule m ∈ [3, n] (3–20 in the reference corpus); the response is a plain m x m nested array with no envelope, row/column order matching `documentIds` as sent.
         */
        post: operations["similarityMatrix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/similarity/{algorithmId}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The complete audit trace for one capability and one document pair
         * @description Returns the **complete** trace with no truncation parameter. The trace pair is identified by two required query parameters, since the path alone does not identify a pair for a GET.
         */
        get: operations["similarityTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clustering": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run hierarchical clustering for one or more linkage criteria
         * @description Returns, per linkage, the (n-1)-row linkage matrix, `leafOrder`, and the evaluation block computed always at the fixed cuts k ∈ {2,3,4,5} ∩ [2, n-1]. There is no `ks` request parameter, so no conforming request can alter the fixed-cut rule.
         */
        post: operations["runClustering"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clustering/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The same computation as /clustering, evaluation block only
         * @description Convenience endpoint; `POST /clustering` already includes this same evaluation block. Same request body and the same fixed-cut rule.
         */
        post: operations["evaluateClustering"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clustering/cut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cut one linkage at a free k (the only free-cut endpoint)
         * @description The only clustering endpoint accepting a free cut. `k` is an integer business rule in [2, n-1] (2–19 in the reference corpus); no height cut exists.
         */
        post: operations["cutClustering"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/embeddings/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status of both embedding families in one response
         * @description One object per capability (`embeddingLocal`, `embeddingApi`), because each reads its own cache and each cache can drift from the corpus independently.
         */
        get: operations["embeddingsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JMH reference-run measurements
         * @description Reads the versioned benchmarks/results/jmh-results.csv and slopes.csv exports as-is; never runs JMH and never recalculates anything. If a results file is missing or malformed the server fails at startup instead of exposing this endpoint, so a successful response always carries real reference-harness data.
         */
        get: operations["benchmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Answers 200 with status UP when the application is healthy.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description One of the six fixed similarity capability ids.
         * @enum {string}
         */
        AlgorithmId: "levenshtein" | "needleman-wunsch" | "jaccard" | "tfidf-cosine" | "embedding-local" | "embedding-api";
        /** @enum {string} */
        AlgorithmKind: "CLASSIC" | "AI";
        /** @enum {string} */
        LinkageId: "single" | "complete" | "average" | "ward";
        /** @description RFC 9457 Problem Detail, as Spring Framework 7 serializes it natively. `type` carries one of this API's fixed URNs, or is entirely absent (never a literal JSON `null`) when the error is one Spring's own machinery classifies without a domain-specific cause. */
        ProblemDetail: {
            /**
             * Format: uri
             * @description A fixed `urn:legajo:problem:*` URN (never a resolvable URL), or omitted entirely for a framework-detected or unexpected error (Spring's default is `about:blank`, which it also omits from the serialized body).
             * @enum {string}
             */
            type?: "urn:legajo:problem:unknown-document" | "urn:legajo:problem:unknown-algorithm" | "urn:legajo:problem:unknown-representation" | "urn:legajo:problem:unknown-linkage" | "urn:legajo:problem:invalid-cut" | "urn:legajo:problem:invalid-selection" | "urn:legajo:problem:embedding-api-unavailable";
            title: string;
            status: number;
            detail?: string;
            /**
             * Format: uri-reference
             * @description Spring populates this with the request path (a relative reference, e.g. `/api/v1/corpus/does-not-exist`), never an absolute URI — `uri-reference` (RFC 3986 URI-reference) is the correct, narrower format for that shape, unlike `type` above, which is always an absolute URN or omitted.
             */
            instance?: string;
        };
        /** @description Spring Boot Actuator's own response shape, not one Legajo defines; `additionalProperties: true` because Actuator can add further keys (e.g. component details when authorized) that this contract does not enumerate. */
        HealthStatus: {
            /** @example UP */
            status: string;
            /** @description The configured health-indicator groups (Actuator's own default field). */
            groups?: string[];
        } & {
            [key: string]: unknown;
        };
        CorpusSummary: {
            id: string;
            title: string;
            authors: string[];
        };
        CorpusDocument: {
            id: string;
            title: string;
            authors: string[];
            abstract: string;
        };
        AlgorithmSummary: {
            id: components["schemas"]["AlgorithmId"];
            displayName: string;
            kind: components["schemas"]["AlgorithmKind"];
        };
        /** @description Common result envelope, as returned over the wire (with `cached`). */
        SimilarityResult: {
            /** Format: double */
            normalizedScore: number;
            /**
             * Format: double
             * @description null only in the documented degenerate cases (e.g. the TF-IDF null vector).
             */
            rawValue?: number | null;
            /** Format: int64 */
            computedNanos: number;
            cached: boolean;
            degenerate: boolean;
        };
        AlgorithmSimilarity: {
            algorithmId: components["schemas"]["AlgorithmId"];
            result: components["schemas"]["SimilarityResult"];
        };
        CompareRequest: {
            documentIdA: string;
            documentIdB: string;
            /** @description Omitted or null defaults to all six capabilities. */
            algorithmIds?: components["schemas"]["AlgorithmId"][] | null;
        };
        MatrixRequest: {
            algorithmId: components["schemas"]["AlgorithmId"];
            /** @description Business rule: size m ∈ [3, n] (3–20 in the reference corpus), no duplicates. */
            documentIds: string[];
        };
        MatrixCell: {
            row: number;
            col: number;
        };
        /**
         * @description MATCH/SUBSTITUTION/INSERTION/DELETION classify a Levenshtein step; MATCH/MISMATCH/GAP classify a Needleman-Wunsch step.
         * @enum {string}
         */
        DpOperationKind: "MATCH" | "SUBSTITUTION" | "INSERTION" | "DELETION" | "MISMATCH" | "GAP";
        DpTraceStep: {
            from: components["schemas"]["MatrixCell"];
            to: components["schemas"]["MatrixCell"];
            operation: components["schemas"]["DpOperationKind"];
        };
        /** @description Shared by `levenshtein` and `needleman-wunsch`. */
        DpMatrixTrace: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            algorithmId: "levenshtein" | "needleman-wunsch";
            rowLabels: string[];
            columnLabels: string[];
            /** @description The complete DP matrix, never truncated. */
            matrix: number[][];
            optimalPath: components["schemas"]["MatrixCell"][];
            operations: components["schemas"]["DpTraceStep"][];
        };
        JaccardTrace: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            algorithmId: "jaccard";
            setA: string[];
            setB: string[];
            intersectionSize: number;
            unionSize: number;
            intersection: string[];
            union: string[];
            /** Format: double */
            coefficient: number;
        };
        TfIdfTermTrace: {
            term: string;
            frequencyA: number;
            frequencyB: number;
            documentFrequency: number;
            /** Format: double */
            tfA: number;
            /** Format: double */
            tfB: number;
            /** Format: double */
            idf: number;
            /** Format: double */
            rawWeightA: number;
            /** Format: double */
            rawWeightB: number;
            /** Format: double */
            normalizedWeightA: number;
            /** Format: double */
            normalizedWeightB: number;
        };
        TfIdfCosineTrace: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            algorithmId: "tfidf-cosine";
            corpusSize: number;
            /** @description Only terms present in at least one of the two compared documents. */
            terms: components["schemas"]["TfIdfTermTrace"][];
            /** Format: double */
            dotProduct: number;
            /** Format: double */
            rawNormA: number;
            /** Format: double */
            rawNormB: number;
            /** Format: double */
            cosine: number;
            /** Format: double */
            angleDegrees: number;
        };
        EmbeddingLocalTrace: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            algorithmId: "embedding-local";
            provider: string;
            model: string;
            dimension: number;
            vectorAExcerpt: number[];
            vectorBExcerpt: number[];
            vectorA: number[];
            vectorB: number[];
            /** Format: double */
            preNormL2A: number;
            /** Format: double */
            preNormL2B: number;
            /** Format: double */
            dotProduct: number;
            /** Format: double */
            cosine: number;
            /** Format: double */
            angleDegrees: number;
            /** Format: double */
            normalizedScore: number;
        };
        EmbeddingApiTrace: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            algorithmId: "embedding-api";
            provider: string;
            model: string;
            dimension: number;
            vectorAExcerpt: number[];
            vectorBExcerpt: number[];
            vectorA: number[];
            vectorB: number[];
            /** Format: double */
            preNormL2A: number;
            /** Format: double */
            preNormL2B: number;
            /** Format: double */
            sumSquaredDiff: number;
            /** Format: double */
            distance: number;
            /** Format: double */
            normalizedScore: number;
            providerStatus: string;
        };
        /** @description One variant per similarity capability. `levenshtein` and `needleman-wunsch` share the `DpMatrixTrace` shape. */
        AlgorithmTrace: components["schemas"]["DpMatrixTrace"] | components["schemas"]["JaccardTrace"] | components["schemas"]["TfIdfCosineTrace"] | components["schemas"]["EmbeddingLocalTrace"] | components["schemas"]["EmbeddingApiTrace"];
        ClusteringRequest: {
            /**
             * @description The vector-space representation (see the shared `Representation` schema); omitted or null defaults to `tfidf-cosine`. Inlined rather than `$ref`'d, since OpenAPI 3.0 does not allow `nullable` as a sibling of `$ref` and the `allOf` workaround for that trips Redocly's `nullable-type-sibling` rule ("the `type` field must be defined when `nullable` is used") — an enum this small is clearer duplicated than wrapped.
             * @enum {string|null}
             */
            representation?: "tfidf-cosine" | "embedding-local" | "embedding-api" | null;
            /** @description Omitted or null defaults to all four. Business rule: non-empty, no unknown ids. */
            linkages?: components["schemas"]["LinkageId"][] | null;
        };
        ClusteringCutRequest: {
            /**
             * @description The vector-space representation (see the shared `Representation` schema); omitted or null defaults to `tfidf-cosine` (see `ClusteringRequest.representation`'s description for why this is inlined rather than `$ref`'d).
             * @enum {string|null}
             */
            representation?: "tfidf-cosine" | "embedding-local" | "embedding-api" | null;
            linkage: components["schemas"]["LinkageId"];
            /** @description Business rule: integer in [2, n-1] (2–19 in the reference corpus). */
            k: number;
        };
        /** @description One row of a linkage matrix. `idx1 < idx2` always. */
        LinkageStep: {
            idx1: number;
            idx2: number;
            /** Format: double */
            mergeDistance: number;
            size: number;
        };
        /** @description `meanSilhouette`/`daviesBouldin` are objects keyed by the fixed cut k (JSON object keys are always strings, e.g. "2".."5") — computed always at k ∈ {2,3,4,5} ∩ [2, n-1]. */
        ClusteringEvaluation: {
            /** Format: double */
            cophenetic: number;
            meanSilhouette: {
                [key: string]: number;
            };
            /** @description null for a k whose centroids coincide. */
            daviesBouldin: {
                [key: string]: number | null;
            };
        };
        LinkageResult: {
            linkageId: components["schemas"]["LinkageId"];
            linkageDisplayName: string;
            /** @description (n-1) rows (19 rows with n = 20). */
            rows: components["schemas"]["LinkageStep"][];
            leafOrder: number[];
            /** @description Length n; position i is the id of the document behind observation i, in the order of corpus.json (the same order GET /corpus lists). idx1/idx2 (< n) and leafOrder index into this same order. */
            documentIds: string[];
            evaluation: components["schemas"]["ClusteringEvaluation"];
        };
        LinkageEvaluation: {
            linkageId: components["schemas"]["LinkageId"];
            linkageDisplayName: string;
            evaluation: components["schemas"]["ClusteringEvaluation"];
        };
        ClusterAssignment: {
            labels: number[];
            k: number;
            /** @description Length n, aligned with labels: documentIds[i] is the document whose cluster is labels[i], in the order of corpus.json (the same order GET /corpus lists). */
            documentIds: string[];
        };
        EmbeddingLocalStatus: {
            provider: string;
            model: string;
            dimension: number;
            corpusSha256: string;
            matchesCorpus: boolean;
            /** @description Fixed literal "cpu" today (CPU-only default). */
            device: string;
        };
        EmbeddingApiStatus: {
            provider: string;
            model: string;
            dimension: number;
            corpusSha256: string;
            matchesCorpus: boolean;
            /**
             * @description The only capability with a live-update path.
             * @enum {string}
             */
            mode: "cached" | "live";
        };
        EmbeddingStatus: {
            embeddingLocal: components["schemas"]["EmbeddingLocalStatus"];
            embeddingApi: components["schemas"]["EmbeddingApiStatus"];
        };
        /** @description The reference-harness metadata recorded in jmh-results.csv's header at JMH run time. Every field is always present: the harness sidecar the export reads from fails closed on a missing key. */
        BenchmarkHarness: {
            cpuModel: string;
            logicalCores: number;
            /** Format: int64 */
            totalRamBytes: number;
            jdk: string;
            os: string;
            /** @description ISO-8601 instant the JMH run finished (the CSV header's utcDate). */
            measuredAt: string;
        };
        /** @description One benchmark method at one parameter value, read as-is from jmh-results.csv. Includes the slo-* families and both embedding-dimension measurements. */
        BenchmarkResult: {
            /** @description Fully qualified JMH benchmark method name. */
            benchmark: string;
            /** @description Curve/family id (e.g. levenshtein, slo-clustering). */
            family: string;
            /** @description Name of the varying @Param this benchmark's size is (e.g. length, n, dimension). */
            parameter: string;
            size: number;
            score: number;
            error: number;
            /** @description JMH throughput/time unit (e.g. ns/op, us/op, ms/op). */
            unit: string;
        };
        /** @description Least-squares log-log slope of one curve family next to its documented theoretical exponent, read as-is from slopes.csv. A fixed-n SLO family is not a curve and never appears here. */
        BenchmarkSlope: {
            family: string;
            points: number;
            empiricalSlope: number;
            theoreticalExponent: number;
        };
        BenchmarkReport: {
            harness: components["schemas"]["BenchmarkHarness"];
            results: components["schemas"]["BenchmarkResult"][];
            slopes: components["schemas"]["BenchmarkSlope"][];
        };
    };
    responses: {
        /** @description A network failure, timeout, rejection, missing API key, or dimension mismatch from the live `embedding-api` provider. Applies to every endpoint that can use the `embedding-api` capability/representation. In live mode, the server fetches missing vectors from the configured OpenAI-compatible embeddings endpoint at request time; any failure of that call is mapped to this response by `ProblemDetailExceptionHandler`. */
        EmbeddingApiUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:legajo:problem:embedding-api-unavailable",
                 *       "title": "Service Unavailable",
                 *       "status": 503,
                 *       "detail": "The live embedding API is currently unavailable."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Any status this operation's explicit responses do not name: a framework-detected client mistake (malformed JSON, missing parameter, unsupported method/media type, unknown route, a blank Bean Validation field — `about:blank`, Spring's own handling) or an unexpected server fault (500, generic detail, no exception message or class name ever exposed). */
        UnexpectedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "title": "Internal Server Error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        CorpusDocumentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCorpus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The n documents of the reference corpus, in corpus order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSummary"][];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    getCorpusDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CorpusDocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The document, including its full abstract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusDocument"];
                };
            };
            /** @description No corpus document with this id (404 because `id` is a path segment). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "urn:legajo:problem:unknown-document",
                     *       "title": "Not Found",
                     *       "status": 404,
                     *       "detail": "no corpus document with id: does-not-exist"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    listSimilarityAlgorithms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The six capabilities, in registration order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlgorithmSummary"][];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    compareSimilarity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description One result per requested (or defaulted) algorithm. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlgorithmSimilarity"][];
                };
            };
            /** @description An unknown `algorithmIds` entry (`unknown-algorithm`), an unknown `documentIdA`/`documentIdB` (`unknown-document`), or a blank required field (`about:blank`, framework-detected) — 400 because these values arrive in the request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            503: components["responses"]["EmbeddingApiUnavailable"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    similarityMatrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixRequest"];
            };
        };
        responses: {
            /** @description An m x m grid; row i, column j is the pair `(documentIds[i], documentIds[j])`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarityResult"][][];
                };
            };
            /** @description An unknown `algorithmId` (`unknown-algorithm`), an unknown entry in `documentIds` (`unknown-document`), or a selection smaller than 3 elements or containing duplicates (`invalid-selection`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            503: components["responses"]["EmbeddingApiUnavailable"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    similarityTrace: {
        parameters: {
            query: {
                documentIdA: string;
                documentIdB: string;
            };
            header?: never;
            path: {
                /** @description One of the six similarity capability ids. */
                algorithmId: components["schemas"]["AlgorithmId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The complete trace; its shape depends on `algorithmId`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlgorithmTrace"];
                };
            };
            /** @description An unknown `documentIdA`/`documentIdB` query value (`unknown-document`) — 400 because these are query parameters, not the path segment. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unknown `algorithmId` path segment (`unknown-algorithm`) — 404 because this value is a path segment. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "urn:legajo:problem:unknown-algorithm",
                     *       "title": "Not Found",
                     *       "status": 404,
                     *       "detail": "no similarity algorithm registered with id: bogus"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            503: components["responses"]["EmbeddingApiUnavailable"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    runClustering: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClusteringRequest"];
            };
        };
        responses: {
            /** @description One `LinkageResult` per requested (or defaulted) linkage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkageResult"][];
                };
            };
            /** @description An unknown `representation` (`unknown-representation`) or an unknown entry in `linkages` (`unknown-linkage`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            503: components["responses"]["EmbeddingApiUnavailable"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    evaluateClustering: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClusteringRequest"];
            };
        };
        responses: {
            /** @description One `LinkageEvaluation` per requested (or defaulted) linkage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkageEvaluation"][];
                };
            };
            /** @description Same causes as `POST /clustering`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            503: components["responses"]["EmbeddingApiUnavailable"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    cutClustering: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusteringCutRequest"];
            };
        };
        responses: {
            /** @description One cluster label per original observation, plus the k they were cut at. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterAssignment"];
                };
            };
            /** @description An unknown `representation` (`unknown-representation`), an unknown `linkage` (`unknown-linkage`), a `k` outside [2, n-1] (`invalid-cut`), or a blank `linkage`/missing `k` (`about:blank`, framework-adjacent validation). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            503: components["responses"]["EmbeddingApiUnavailable"];
            default: components["responses"]["UnexpectedError"];
        };
    };
    embeddingsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Both families' status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingStatus"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    benchmarks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reference harness plus every classified result and curve slope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkReport"];
                };
            };
            default: components["responses"]["UnexpectedError"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The application is up. Served as `application/vnd.spring-boot.actuator.v3+json` when the caller sends no `Accept` header (Spring's default content negotiation for actuator endpoints prefers this vendor type first), or as plain `application/json` when the caller explicitly requests it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.spring-boot.actuator.v3+json": components["schemas"]["HealthStatus"];
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
